export interface PetCareServiceDetail {
  id: string;
  name: string;
  subcategory: string;
  price: number;
  duration: number;
  image: string;
  shortDescription: string;
  fullDescription: string;
  whatIsIncluded: string[];
  steps: string[];
  productsUsed: string[];
  benefits: string[];
  suitableFor: string[];
  frequency: string;
}

export const PET_CARE_SERVICES: PetCareServiceDetail[] = [
  // GROOMING - DOGS
  {
    id: "basic-grooming-dog",
    name: "Basic Grooming (Dog)",
    subcategory: "Grooming",
    price: 90000,
    duration: 60,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80",
    shortDescription: "Essential grooming service for dogs including bath, brush, nail trim, and ear cleaning",
    fullDescription: "Our basic grooming package provides comprehensive care for your dog's hygiene and appearance. Perfect for maintaining your pet's coat health and cleanliness between full grooming sessions. Our professional groomers use premium, pet-safe products tailored to your dog's coat type and skin sensitivity.",
    whatIsIncluded: [
      "Warm water bath with premium shampoo",
      "Thorough coat brushing and de-shedding",
      "Nail trimming and filing",
      "Ear cleaning and inspection",
      "Paw pad care and moisturizing",
      "Basic sanitary trim",
    ],
    steps: [
      "Initial consultation to understand your dog's temperament and any special needs",
      "Pre-bath brushing to remove loose fur and detangle coat",
      "Gentle bath using breed-appropriate shampoo and conditioner",
      "Thorough rinse to ensure no product residue",
      "Towel dry and blow dry with pet-safe equipment",
      "Nail trimming with professional-grade clippers",
      "Ear cleaning using veterinary-approved solution",
      "Final brush and coat inspection",
    ],
    productsUsed: [
      "Hypoallergenic dog shampoo (pH-balanced for canine skin)",
      "Moisturizing conditioner for coat health",
      "Natural ear cleaning solution",
      "Paw balm for pad protection",
      "De-shedding tools and slicker brushes",
      "Professional pet nail clippers",
    ],
    benefits: [
      "Maintains healthy skin and coat condition",
      "Prevents matting and reduces shedding",
      "Early detection of skin issues or parasites",
      "Improved hygiene and reduced odor",
      "Prevents nail overgrowth and associated pain",
      "Reduces risk of ear infections",
    ],
    suitableFor: [
      "All dog breeds and sizes",
      "Dogs with short to medium coat length",
      "Puppies 12 weeks and older",
      "Senior dogs needing gentle care",
      "Dogs between full grooming appointments",
    ],
    frequency: "Every 4-6 weeks, or as recommended by your groomer based on breed and lifestyle",
  },
  {
    id: "full-grooming-dog",
    name: "Full Grooming (Dog)",
    subcategory: "Grooming",
    price: 185000,
    duration: 120,
    image: "https://images.unsplash.com/photo-1616013476506-12be68c3179f?w=800&q=80",
    shortDescription: "Complete grooming service including bath, haircut, styling, nail trim, and ear cleaning",
    fullDescription: "Our premium full grooming service provides everything your dog needs to look and feel their best. This comprehensive package includes professional styling tailored to your dog's breed standards or your personal preferences, along with complete hygiene care.",
    whatIsIncluded: [
      "Premium bath with specialized shampoo and conditioner",
      "Professional haircut and styling",
      "Complete de-shedding treatment",
      "Nail trim, filing, and paw pad grooming",
      "Ear cleaning and plucking (if needed)",
      "Teeth brushing",
      "Sanitary and hygiene trim",
      "Cologne or deodorizing spray",
      "Bow or bandana accessory",
    ],
    steps: [
      "Consultation on desired style and breed-specific cuts",
      "Pre-grooming health check and coat assessment",
      "De-matting and de-shedding treatment",
      "Luxury bath with massage technique",
      "Blow dry and fluff dry for volume",
      "Precision haircut according to breed standard or custom style",
      "Face, paw, and sanitary area trimming",
      "Nail care and paw pad hair removal",
      "Ear cleaning and maintenance",
      "Teeth brushing with pet-safe toothpaste",
      "Final styling and finishing touches",
      "Optional cologne or bow accessory",
    ],
    productsUsed: [
      "Premium breed-specific shampoo",
      "Deep conditioning treatment",
      "De-shedding solution",
      "Professional grooming scissors and clippers",
      "Ear cleansing solution",
      "Pet-safe toothpaste and toothbrush",
      "Paw balm and pad moisturizer",
      "Finishing spray and cologne",
    ],
    benefits: [
      "Professional breed-standard or custom styling",
      "Complete hygiene and health maintenance",
      "Reduced shedding for 3-4 weeks",
      "Improved coat texture and shine",
      "Early detection of health issues",
      "Enhanced comfort through mat removal",
      "Fresh, clean scent that lasts",
    ],
    suitableFor: [
      "All dog breeds, especially long-haired breeds",
      "Dogs needing breed-standard styling",
      "Show dogs and special occasion prep",
      "Dogs with matted or tangled coats",
      "Seasonal coat changes and heavy shedding periods",
    ],
    frequency: "Every 6-8 weeks for most breeds, every 4-6 weeks for breeds with continuously growing hair",
  },
  {
    id: "bath-blow-dry-dog",
    name: "Bath & Blow Dry (Dog)",
    subcategory: "Grooming",
    price: 75000,
    duration: 60,
    image: "https://images.unsplash.com/photo-1585559700398-1385b3a8aeb6?w=800&q=80",
    shortDescription: "Refreshing bath and professional blow dry to keep your dog clean and fresh",
    fullDescription: "A thorough cleaning service perfect for dogs who don't need a full haircut but require regular bathing. Our bath and blow dry service uses premium products and professional drying techniques to leave your dog's coat clean, fluffy, and smelling great.",
    whatIsIncluded: [
      "Pre-bath brushing and de-tangling",
      "Warm water bath with premium shampoo",
      "Conditioning treatment",
      "Thorough rinse",
      "Towel drying",
      "Professional blow dry and fluff",
      "Light brushing to finish",
    ],
    steps: [
      "Assessment of coat condition and any problem areas",
      "Gentle pre-bath brushing to remove loose fur",
      "Warm water bath with gentle massage",
      "Application of breed-appropriate shampoo",
      "Conditioning treatment for coat health",
      "Complete rinse to remove all product",
      "Towel dry to remove excess water",
      "Professional blow dry using pet-safe dryer",
      "Final brush and fluff for volume",
    ],
    productsUsed: [
      "Natural dog shampoo (oatmeal, aloe, or tea tree options)",
      "Moisturizing conditioner",
      "Detangling spray",
      "Professional pet-safe blow dryer",
      "Slicker brush and finishing comb",
    ],
    benefits: [
      "Removes dirt, debris, and odors",
      "Maintains coat health between full grooms",
      "Reduces allergens in the home",
      "Promotes healthy skin",
      "Helps identify any skin issues early",
      "Leaves coat soft, shiny, and manageable",
    ],
    suitableFor: [
      "Dogs with short coats not needing haircuts",
      "Active dogs who get dirty frequently",
      "Dogs with seasonal shedding",
      "Between full grooming appointments",
      "Senior dogs needing gentle refreshing",
    ],
    frequency: "Every 2-4 weeks depending on activity level and coat type",
  },
  {
    id: "nail-ear-care-dog",
    name: "Nail Trim & Ear Cleaning (Dog)",
    subcategory: "Grooming",
    price: 25000,
    duration: 20,
    image: "https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?w=800&q=80",
    shortDescription: "Essential maintenance for your dog's nails and ears to prevent health issues",
    fullDescription: "Regular nail and ear care is crucial for your dog's comfort and health. Our professional service ensures proper nail length and clean, healthy ears, preventing painful overgrowth and potential infections.",
    whatIsIncluded: [
      "Nail trimming to appropriate length",
      "Nail filing for smooth edges",
      "Paw pad inspection and hair trimming",
      "Ear inspection for signs of infection",
      "Gentle ear cleaning",
      "Ear drying and finishing",
    ],
    steps: [
      "Visual inspection of nails and quick location",
      "Careful trimming avoiding the quick",
      "Filing sharp edges for smoothness",
      "Paw pad hair trimming if needed",
      "Ear examination for redness, odor, or discharge",
      "Gentle cleaning with veterinary-approved solution",
      "Removal of excess wax and debris",
      "Thorough drying to prevent moisture buildup",
    ],
    productsUsed: [
      "Professional pet nail clippers or grinder",
      "Nail file or grinder attachment",
      "Veterinary-approved ear cleaning solution",
      "Soft cotton pads",
      "Styptic powder (for accidental quick cuts)",
    ],
    benefits: [
      "Prevents painful nail overgrowth",
      "Reduces scratching and damage to furniture",
      "Improves walking comfort and posture",
      "Prevents ear infections",
      "Removes excess wax and debris",
      "Early detection of ear problems",
    ],
    suitableFor: [
      "All dogs requiring nail and ear maintenance",
      "Dogs between grooming appointments",
      "Dogs who don't naturally wear down nails",
      "Breeds prone to ear infections (floppy ears)",
      "Quick maintenance without full grooming",
    ],
    frequency: "Nails: Every 3-4 weeks, Ears: Every 2-4 weeks or as needed",
  },

  // GROOMING - CATS
  {
    id: "basic-grooming-cat",
    name: "Basic Grooming (Cat)",
    subcategory: "Grooming",
    price: 70000,
    duration: 45,
    image: "https://images.unsplash.com/photo-1529257414772-1960b7bea4eb?w=800&q=80",
    shortDescription: "Gentle grooming service for cats including bath, brush, nail trim, and ear cleaning",
    fullDescription: "Our cat-specific basic grooming service is designed with feline comfort in mind. We use gentle techniques and cat-safe products to ensure a stress-free experience while maintaining your cat's hygiene and coat health.",
    whatIsIncluded: [
      "Gentle brushing and de-shedding",
      "Warm water bath with cat-safe shampoo",
      "Nail trimming",
      "Ear cleaning",
      "Eye cleaning",
      "Sanitary trim (if needed)",
    ],
    steps: [
      "Calm introduction and stress assessment",
      "Gentle pre-bath brushing to remove loose fur and mats",
      "Lukewarm bath using feline-specific shampoo",
      "Quick but thorough rinse",
      "Towel dry (most cats don't require blow drying)",
      "Careful nail trimming of front and back claws",
      "Gentle ear cleaning with cat-safe solution",
      "Eye cleaning to remove tear stains",
      "Final brush and coat check",
    ],
    productsUsed: [
      "pH-balanced cat shampoo (no essential oils)",
      "Tearless facial cleanser",
      "Cat-specific nail clippers",
      "Feline ear cleaning solution",
      "Soft slicker brush for cats",
      "De-shedding tool",
    ],
    benefits: [
      "Reduces hairballs through de-shedding",
      "Maintains healthy skin and coat",
      "Prevents nail overgrowth and furniture damage",
      "Reduces dander and allergens",
      "Prevents ear mites and infections",
      "Stress-free alternative to home grooming",
    ],
    suitableFor: [
      "All cat breeds and ages (8 weeks+)",
      "Short to medium-haired cats",
      "Cats who groom themselves but need extra help",
      "Indoor cats with minimal grooming needs",
      "Senior cats unable to groom effectively",
    ],
    frequency: "Every 6-8 weeks for most cats, more frequent for long-haired breeds",
  },
  {
    id: "full-grooming-cat",
    name: "Full Grooming (Cat)",
    subcategory: "Grooming",
    price: 150000,
    duration: 90,
    image: "https://images.unsplash.com/photo-1573865526739-10c1d3a1f0cc?w=800&q=80",
    shortDescription: "Complete grooming service for cats including bath, haircut (if needed), nail trim, and full hygiene care",
    fullDescription: "Our comprehensive cat grooming service provides everything your feline friend needs for optimal health and appearance. Especially beneficial for long-haired breeds or cats with matting issues, this service includes gentle de-matting, optional haircut, and complete hygiene care.",
    whatIsIncluded: [
      "De-matting and thorough brushing",
      "Premium bath with feline-specific products",
      "Haircut or lion cut (if requested/needed)",
      "Nail trim and filing",
      "Ear cleaning and plucking",
      "Eye cleaning",
      "Sanitary trim",
      "Teeth brushing (if tolerated)",
      "Paw pad care",
    ],
    steps: [
      "Consultation on cat's temperament and grooming needs",
      "Gentle de-matting with specialized tools",
      "Pre-bath brushing to remove loose undercoat",
      "Warm bath with feline massage techniques",
      "Conditioning treatment for long-haired breeds",
      "Towel drying (blow dry only if cat is comfortable)",
      "Haircut or lion cut if requested",
      "Precision trimming around face, paws, and sanitary areas",
      "Nail trimming and filing",
      "Ear cleaning and light plucking if needed",
      "Eye area cleaning",
      "Teeth brushing with cat-safe paste",
      "Final brush and styling",
    ],
    productsUsed: [
      "Premium cat shampoo (hypoallergenic)",
      "Conditioning spray for long-haired cats",
      "Professional de-matting tools",
      "Cat-safe grooming scissors and clippers",
      "Nail clippers and file",
      "Feline ear solution",
      "Enzymatic cat toothpaste",
      "Paw pad moisturizer",
    ],
    benefits: [
      "Complete mat removal for comfort",
      "Professional breed-specific or lion cut styling",
      "Significant reduction in shedding",
      "Prevention of hairballs",
      "Improved skin health",
      "Early detection of skin conditions or parasites",
      "Stress-free professional care",
    ],
    suitableFor: [
      "Long-haired cat breeds (Persian, Maine Coon, Ragdoll)",
      "Cats with severe matting",
      "Cats requiring lion cuts for summer or medical reasons",
      "Show cats needing breed-standard grooming",
      "Cats with special grooming needs",
    ],
    frequency: "Every 6-12 weeks for long-haired breeds, every 3-4 months for short-haired cats",
  },
  {
    id: "bath-blow-dry-cat",
    name: "Bath & Blow Dry (Cat)",
    subcategory: "Grooming",
    price: 60000,
    duration: 45,
    image: "https://images.unsplash.com/photo-1611003228941-98852ba62227?w=800&q=80",
    shortDescription: "Gentle bath and drying service to keep your cat clean and reduce shedding",
    fullDescription: "A specialized bathing service designed specifically for cats who need cleaning but don't require a full haircut. We use low-stress techniques and cat-safe products to ensure your feline stays calm throughout the process.",
    whatIsIncluded: [
      "Pre-bath brushing",
      "Gentle cat-specific bath",
      "Conditioning treatment",
      "Towel drying",
      "Optional low-heat blow dry (if cat tolerates)",
      "Final brushing",
    ],
    steps: [
      "Calm environment setup with pheromone spray",
      "Gentle pre-bath brushing",
      "Lukewarm water introduction gradually",
      "Application of tearless cat shampoo",
      "Thorough rinse avoiding face area",
      "Gentle towel drying",
      "Low-stress blow dry if cat is comfortable (many cats air dry)",
      "Final brush to fluff coat",
    ],
    productsUsed: [
      "Tearless cat shampoo",
      "Conditioning spray",
      "Calming pheromone spray",
      "Soft microfiber towels",
      "Low-noise pet dryer (if used)",
      "Cat-specific grooming brushes",
    ],
    benefits: [
      "Removes excess oils and dander",
      "Reduces allergens in the home",
      "Helps during heavy shedding seasons",
      "Maintains coat health",
      "Provides relief for cats who can't groom themselves",
      "Low-stress alternative to home bathing",
    ],
    suitableFor: [
      "Cats who get into messy situations",
      "Senior cats unable to self-groom",
      "Overweight cats with grooming difficulties",
      "Cats with skin conditions requiring medicated baths",
      "Show cats needing fresh appearance",
    ],
    frequency: "Every 4-6 months for most cats, more frequent if medically necessary",
  },
  {
    id: "nail-ear-care-cat",
    name: "Nail Trim & Ear Cleaning (Cat)",
    subcategory: "Grooming",
    price: 20000,
    duration: 15,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&q=80",
    shortDescription: "Quick and gentle nail trimming and ear cleaning for cats",
    fullDescription: "Essential maintenance service for indoor cats who don't naturally wear down their claws, and for all cats to maintain ear health. Our gentle approach ensures minimal stress for your feline friend.",
    whatIsIncluded: [
      "All four paws nail trimming",
      "Nail inspection for issues",
      "Ear inspection",
      "Gentle ear cleaning",
      "Eye cleaning if needed",
    ],
    steps: [
      "Calm handling with gentle restraint techniques",
      "Inspection of each nail and quick location",
      "Trimming of front and back claws",
      "Check for split or damaged nails",
      "Ear examination for mites, infection, or excess wax",
      "Gentle cleaning with cat-safe solution",
      "Removal of visible debris",
      "Eye area wipe if tearstaining present",
    ],
    productsUsed: [
      "Cat-specific nail clippers (scissor or guillotine style)",
      "Feline ear cleaning solution",
      "Soft cotton balls or pads",
      "Styptic powder for safety",
      "Tear stain remover wipes",
    ],
    benefits: [
      "Prevents furniture and upholstery damage",
      "Reduces accidental scratches to humans",
      "Prevents ingrown nails",
      "Early detection of ear mites or infections",
      "Removes excess wax buildup",
      "Professional care without full grooming commitment",
    ],
    suitableFor: [
      "Indoor cats of all ages",
      "Cats who scratch furniture",
      "Cats with overgrown nails",
      "Cats prone to ear issues",
      "Quick maintenance between grooming",
    ],
    frequency: "Nails: Every 2-4 weeks, Ears: Monthly or as needed based on wax buildup",
  },

  // WALKING
  {
    id: "walk-15min",
    name: "15-Minute Walk",
    subcategory: "Walking",
    price: 22500,
    duration: 15,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
    shortDescription: "Quick neighborhood walk perfect for puppies or senior dogs",
    fullDescription: "A brief but beneficial walk designed for dogs who need light exercise, bathroom breaks, or gentle activity. Perfect for puppies, senior dogs, or as a midday bathroom break.",
    whatIsIncluded: [
      "15 minutes of walking time",
      "Bathroom break opportunity",
      "Light exercise and fresh air",
      "GPS tracked walk",
      "Post-walk update with photos",
    ],
    steps: [
      "Meet and greet with your dog",
      "Secure leash attachment and safety check",
      "Walk around the neighborhood at appropriate pace",
      "Allow time for bathroom breaks",
      "Return home safely",
      "Fresh water provided if needed",
      "Send update message with walk details and photos",
    ],
    productsUsed: [
      "Professional-grade leash and harness",
      "Waste bags and disposal",
      "GPS tracking app",
      "Treats for positive reinforcement (with owner permission)",
    ],
    benefits: [
      "Midday bathroom break relief",
      "Gentle exercise for puppies or seniors",
      "Mental stimulation through neighborhood exploration",
      "Socialization opportunity",
      "Reliable service when you're busy",
    ],
    suitableFor: [
      "Puppies under 6 months",
      "Senior dogs with limited mobility",
      "Small breed dogs",
      "Dogs recovering from injury",
      "Midday bathroom breaks",
    ],
    frequency: "Daily for puppies, 1-2 times daily for adult dogs, as needed for seniors",
  },
  {
    id: "walk-30min",
    name: "30-Minute Walk",
    subcategory: "Walking",
    price: 35000,
    duration: 30,
    image: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&q=80",
    shortDescription: "Standard walk providing good exercise and bathroom breaks",
    fullDescription: "Our most popular walking service offering the ideal balance of exercise, exploration, and bathroom breaks. Perfect for most adult dogs' daily exercise needs.",
    whatIsIncluded: [
      "30 minutes of quality walking time",
      "Multiple bathroom break opportunities",
      "Moderate exercise and mental stimulation",
      "GPS tracked route",
      "Photo updates",
      "Fresh water upon return",
    ],
    steps: [
      "Greeting and initial energy assessment",
      "Secure harness/leash attachment",
      "30-minute walk through neighborhood or park",
      "Varied route for mental stimulation",
      "Multiple potty break opportunities",
      "Basic obedience reinforcement during walk",
      "Safe return and removal of walking gear",
      "Fresh water and brief play if time permits",
      "Detailed walk report with GPS map and photos",
    ],
    productsUsed: [
      "Professional walking harness",
      "6-foot walking leash",
      "Waste bags",
      "GPS tracking device/app",
      "Portable water bowl (for hot days)",
      "Training treats",
    ],
    benefits: [
      "Adequate daily exercise for most breeds",
      "Mental stimulation through exploration",
      "Socialization with other dogs and people",
      "Reduces destructive behavior at home",
      "Maintains healthy weight",
      "Strengthens bond through positive experience",
    ],
    suitableFor: [
      "Adult dogs of all sizes",
      "Active dogs needing daily exercise",
      "Dogs with moderate energy levels",
      "Working dog owners needing midday walks",
      "Dogs requiring routine and structure",
    ],
    frequency: "Once or twice daily for optimal exercise and routine",
  },
  {
    id: "walk-60min",
    name: "60-Minute Walk",
    subcategory: "Walking",
    price: 55000,
    duration: 60,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80",
    shortDescription: "Extended walk for high-energy dogs needing substantial exercise",
    fullDescription: "An extended walking session perfect for high-energy breeds, active dogs, or those requiring significant daily exercise. This walk includes varied terrain, play breaks, and comprehensive exercise to tire out even the most energetic pups.",
    whatIsIncluded: [
      "Full hour of walking and exercise",
      "Park visit or varied terrain",
      "Play breaks and mental stimulation games",
      "Multiple bathroom opportunities",
      "GPS tracked adventure",
      "Comprehensive photo update",
      "Post-walk care (water, towel dry if wet)",
    ],
    steps: [
      "Pre-walk energy assessment and stretching",
      "Secure gear and safety check",
      "Varied route with different terrains and experiences",
      "Visit to dog-friendly park or trail",
      "Play breaks with fetch or tug toys",
      "Mental enrichment through sniff walks and exploration",
      "Social interaction with other dogs if appropriate",
      "Multiple potty breaks throughout",
      "Cool-down period in final 10 minutes",
      "Return home, paw cleaning if muddy",
      "Fresh water and rest time",
      "Detailed report with GPS tracking, photos, and notes",
    ],
    productsUsed: [
      "Heavy-duty walking harness",
      "Long line or standard leash (based on training level)",
      "Waste bags",
      "Interactive toys (ball, frisbee, tug rope)",
      "Portable water bottle and bowl",
      "GPS tracking app",
      "Training treats and rewards",
      "Paw wipes for muddy adventures",
    ],
    benefits: [
      "Comprehensive exercise for high-energy breeds",
      "Significant mental stimulation through varied environment",
      "Socialization opportunities in parks",
      "Reduces anxiety and destructive behavior",
      "Maintains optimal physical fitness",
      "Adventure and enrichment",
      "Returns home tired and content",
    ],
    suitableFor: [
      "High-energy breeds (Border Collies, Huskies, Labs, etc.)",
      "Working breeds requiring substantial exercise",
      "Young adult dogs (1-7 years)",
      "Dogs training for activities or competitions",
      "Active owners wanting comprehensive care on busy days",
    ],
    frequency: "Daily for high-energy breeds, 3-4 times weekly for moderately active dogs",
  },

  // SITTING & HOME VISITS
  {
    id: "pet-sitting-hourly",
    name: "Pet Sitting (Hourly)",
    subcategory: "Sitting & Home Visits",
    price: 45000,
    duration: 60,
    image: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800&q=80",
    shortDescription: "Personalized in-home pet care and companionship by the hour",
    fullDescription: "Professional in-home pet sitting providing companionship, care, and peace of mind while you're away. Our sitters follow your pet's normal routine, administer medications if needed, and provide plenty of love and attention.",
    whatIsIncluded: [
      "One hour of personalized care and attention",
      "Feeding and fresh water",
      "Playtime and exercise",
      "Medication administration (if needed)",
      "Litter box cleaning (cats)",
      "Indoor play or backyard time",
      "Photo and video updates",
      "Light home security checks",
    ],
    steps: [
      "Arrival and greeting (respecting shy pets' space)",
      "Feeding according to your schedule and portions",
      "Fresh water replenishment",
      "Medication administration if required",
      "30-40 minutes of active play and attention",
      "For dogs: backyard potty break or short walk",
      "For cats: litter box cleaning and freshening",
      "Interactive play with favorite toys",
      "Brushing or petting time",
      "Home security check (mail, lights, temperature)",
      "Departure with love and reassurance",
      "Detailed text/photo update to owner",
    ],
    productsUsed: [
      "Your pet's own food and bowls",
      "Favorite toys and enrichment items",
      "Medication (owner-provided with instructions)",
      "Litter box supplies",
      "Treats for positive reinforcement",
    ],
    benefits: [
      "Pets remain comfortable in their own environment",
      "Maintains normal routine and reduces stress",
      "One-on-one personalized attention",
      "Medication administration by trained professional",
      "Home security presence",
      "Avoids kennel stress and disease exposure",
      "Perfect for anxious or senior pets",
    ],
    suitableFor: [
      "Cats preferring to stay home",
      "Dogs with separation anxiety",
      "Senior pets needing special care",
      "Pets on medication schedules",
      "Multiple pet households",
      "Pets uncomfortable in boarding facilities",
    ],
    frequency: "1-3 times daily depending on pet's needs and your schedule",
  },
  {
    id: "pet-day-care",
    name: "Pet Day Care",
    subcategory: "Sitting & Home Visits",
    price: 225000,
    duration: 480,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?w=800&q=80",
    shortDescription: "Full 8-hour day care service keeping your pet happy, safe, and entertained",
    fullDescription: "Comprehensive full-day pet care in your home, perfect for long work days or travel. Your pet receives constant supervision, multiple meals, exercise, playtime, and all the care they need for a full day, all in the comfort of their own home.",
    whatIsIncluded: [
      "8 hours of continuous care and supervision",
      "Multiple feeding times according to schedule",
      "2-3 walks or play sessions",
      "Medication administration throughout the day",
      "Litter maintenance and home cleanup",
      "Mental stimulation and enrichment activities",
      "Regular photo and video updates",
      "Full home security monitoring",
      "End-of-day report",
    ],
    steps: [
      "Morning arrival and warm greeting",
      "Breakfast feeding if scheduled",
      "Morning walk or energetic play session (30-45 min)",
      "Mental enrichment activities (puzzle toys, training)",
      "Midday feeding and medication if needed",
      "Afternoon walk or backyard play",
      "Quiet time for rest",
      "Light training or trick practice",
      "Late afternoon potty break and activity",
      "Evening feeding if scheduled",
      "Final walk or play session",
      "Home cleanup (toys, dishes, litter)",
      "Settle pet for evening",
      "Comprehensive daily report with photos",
    ],
    productsUsed: [
      "Pet's regular food and feeding schedule",
      "All medications with detailed instructions",
      "Variety of toys and enrichment items",
      "Grooming tools for light brushing",
      "Cleaning supplies for accidents",
      "Puzzle feeders and interactive toys",
    ],
    benefits: [
      "Complete peace of mind during long absences",
      "Prevents loneliness and separation anxiety",
      "Maintains pet's normal routine",
      "Comprehensive exercise and mental stimulation",
      "Home security presence all day",
      "Prevents destructive behavior from boredom",
      "Medical monitoring throughout the day",
      "Perfect alternative to boarding",
    ],
    suitableFor: [
      "Dogs who can't be left alone all day",
      "Puppies requiring frequent potty breaks",
      "Senior pets needing monitoring",
      "Pets recovering from surgery or illness",
      "High-energy dogs needing exercise",
      "Anxious pets requiring companionship",
      "Multiple pet households",
    ],
    frequency: "Weekdays for working owners, or as needed for special circumstances",
  },
  {
    id: "home-checkin",
    name: "Home Check-In (Food, Water, Litter)",
    subcategory: "Sitting & Home Visits",
    price: 30000,
    duration: 30,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80",
    shortDescription: "Quick visit to provide food, fresh water, and basic care",
    fullDescription: "A brief but thorough check-in visit perfect for independent cats or pets who don't require extended companionship. Ensures your pet has fresh food and water, clean litter, and a quick wellness check.",
    whatIsIncluded: [
      "30-minute home visit",
      "Fresh food and water",
      "Litter box scooping (cats)",
      "Quick potty break (dogs)",
      "Medication administration if needed",
      "5-10 minutes of attention/petting",
      "Quick photo update",
      "Home security check",
    ],
    steps: [
      "Arrival and greeting",
      "Provide fresh food according to instructions",
      "Clean and refill water bowls",
      "Scoop litter box and check for abnormalities",
      "For dogs: quick potty break in yard or short walk",
      "Administer any medications",
      "Brief playtime or petting",
      "Visual health check",
      "Home security check (lights, doors, thermostat)",
      "Quick cleanup of feeding area",
      "Text update with photo to owner",
    ],
    productsUsed: [
      "Pet's food and bowls",
      "Fresh water",
      "Litter box supplies",
      "Medications if required",
      "Treats for positive interaction",
    ],
    benefits: [
      "Affordable option for independent pets",
      "Ensures basic needs are met",
      "Quick wellness check",
      "Litter maintenance for cleanliness",
      "Home security presence",
      "Perfect for weekend trips or long work days",
    ],
    suitableFor: [
      "Independent cats",
      "Adult dogs with access to yard",
      "Pets comfortable with brief alone time",
      "Weekend getaways",
      "Supplemental care between longer visits",
      "Multi-pet households with simple needs",
    ],
    frequency: "1-2 times daily for cats, 2-3 times daily for dogs, depending on absence length",
  },

  // TRAINING
  {
    id: "puppy-training",
    name: "Puppy Training Session",
    subcategory: "Training",
    price: 115000,
    duration: 60,
    image: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&q=80",
    shortDescription: "Foundation training for puppies including basic commands and socialization",
    fullDescription: "Professional puppy training focusing on essential obedience, socialization, and positive behavior development. Our force-free, reward-based methods set your puppy up for a lifetime of good behavior and strong bonding with you.",
    whatIsIncluded: [
      "One hour of structured training",
      "Basic commands (sit, stay, come, down)",
      "Leash training and walking manners",
      "Socialization techniques",
      "House training guidance",
      "Bite inhibition and mouthing control",
      "Crate training basics",
      "Training homework for the week",
      "Progress report and next steps",
    ],
    steps: [
      "Assessment of puppy's current training level and temperament",
      "Introduction to positive reinforcement techniques",
      "Practice 'sit' command with treats and praise",
      "Work on 'come' command with recall games",
      "Leash training with loose-leash walking",
      "Socialization exposure to sights, sounds, textures",
      "Bite inhibition training through gentle redirection",
      "Short attention span breaks with play",
      "Owner education on continuing training at home",
      "Assign homework exercises for the week",
      "Q&A session for specific concerns",
    ],
    productsUsed: [
      "High-value training treats (small, soft)",
      "Clicker for marker training",
      "6-foot training leash",
      "Variety of toys for reward",
      "Training treats pouch",
    ],
    benefits: [
      "Establishes foundation for lifelong good behavior",
      "Builds confidence and reduces fear",
      "Prevents common behavior problems before they start",
      "Strengthens owner-puppy bond",
      "Provides essential socialization during critical period",
      "Teaches impulse control and manners",
      "Creates well-adjusted adult dog",
    ],
    suitableFor: [
      "Puppies 8 weeks to 6 months old",
      "First-time dog owners",
      "Puppies showing early behavior concerns",
      "Socialization during critical developmental period",
      "Foundation before advanced training",
    ],
    frequency: "Weekly sessions for 6-8 weeks for complete foundation training",
  },
  {
    id: "behavior-consultation",
    name: "Behavior Consultation",
    subcategory: "Training",
    price: 160000,
    duration: 90,
    image: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&q=80",
    shortDescription: "Professional assessment and training plan for behavior issues",
    fullDescription: "Comprehensive behavior consultation for dogs exhibiting problematic behaviors. Our certified trainers assess the root cause, develop a customized behavior modification plan, and provide hands-on training to address issues like aggression, anxiety, excessive barking, and more.",
    whatIsIncluded: [
      "90-minute in-depth consultation",
      "Detailed behavior assessment",
      "Discussion of history and triggers",
      "Customized behavior modification plan",
      "Hands-on demonstration of techniques",
      "Owner training and education",
      "Written plan with daily exercises",
      "Follow-up support via email/text",
      "Resource materials",
    ],
    steps: [
      "Detailed intake questionnaire about behavior history",
      "Observation of dog in home environment",
      "Discussion of specific behavior concerns and triggers",
      "Assessment of dog's body language and stress signals",
      "Identification of root causes (fear, anxiety, lack of training, etc.)",
      "Development of customized behavior modification protocol",
      "Demonstration of training techniques",
      "Practice session with owner participation",
      "Discussion of management strategies",
      "Creation of daily training schedule",
      "Q&A and troubleshooting",
      "Set goals and timeline for improvement",
      "Schedule follow-up check-in",
    ],
    productsUsed: [
      "High-value treats for counter-conditioning",
      "Clicker for precise marking",
      "Various training aids specific to behavior issue",
      "Calming aids (pheromones, anxiety wraps) if recommended",
      "Management tools (gates, crates, leashes)",
    ],
    benefits: [
      "Professional diagnosis of behavior problems",
      "Customized solution for your specific situation",
      "Improved quality of life for dog and family",
      "Prevention of behavior escalation",
      "Increased safety for household and public",
      "Reduced stress and anxiety for the dog",
      "Better understanding of canine behavior",
      "Strengthened owner-dog relationship",
    ],
    suitableFor: [
      "Dogs with aggression issues (toward people or dogs)",
      "Severe separation anxiety",
      "Excessive barking or reactivity",
      "Fear-based behaviors",
      "Resource guarding",
      "Destructive behaviors",
      "Compulsive behaviors",
      "Newly adopted dogs with unknown history",
    ],
    frequency: "Initial consultation followed by 2-4 follow-up sessions depending on behavior severity",
  },
];

export function getPetCareServiceDetail(serviceId: string): PetCareServiceDetail | undefined {
  return PET_CARE_SERVICES.find(service => service.id === serviceId);
}
